version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes: 
      - ./front:/app
    command: yarn dev
    ports:
      - "3000:3000"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes: 
      - ./back:/server
    command: uvicorn main:app --reload --host 0.0.0.0
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
   image: mysql
   environment:
     - MYSQL_ROOT_PASSWORD=password
